export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const FETCH_NEWS_BEGIN = "FETCH_NEWS_BEGIN";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";

export const FETCH_REFEREES_BEGIN = "FETCH_REFEREES_BEGIN";
export const FETCH_REFEREES_SUCCESS = "FETCH_REFEREES_SUCCESS";
export const FETCH_REFEREES_FAILURE = "FETCH_REFEREES_FAILURE";

export const FETCH_MATCHES_BEGIN = "FETCH_MATCHES_BEGIN";
export const FETCH_MATCHES_SUCCESS = "FETCH_MATCHES_SUCCESS";
export const FETCH_MATCHES_FAILURE = "FETCH_MATCHES_FAILURE";
