module.exports = {
  MATCH_STUBS: [
    {
      matchNumber: 300,
      homeTeamName: 'SCMU Craiova',
      awayTeamName: 'CS U Cluj',
      dateString: '2019-02-19',
      locality: 'Campia Turzii',
      A1: 'Coman Mihai',
      A2: 'Santa Cristian',
    },
    {
      matchNumber: 301,
      homeTeamName: 'CSA Steaua Bucuresti',
      awayTeamName: 'CSM Campia Turzii',
      dateString: '2018-11-17',
      locality: 'Craiova',
      A1: 'Prodana Alexandru',
      A2: 'Jianu Violeta',
    },
    {
      matchNumber: 302,
      homeTeamName: 'CS Dinamo Bucuresti',
      awayTeamName: 'CSM Bucuresti',
      dateString: '2018-12-16',
      locality: 'Campia Turzii',
      A1: 'Nastase Lucian',
      A2: 'Jianu Violeta',
    },
    {
      matchNumber: 303,
      homeTeamName: 'ACS Volei Municipal Zalau',
      awayTeamName: 'CS Stiinta Explorari Baia Mare',
      dateString: '2019-01-15',
      locality: 'Craiova',
      A1: 'Prodana Alexandru',
      A2: 'Santa Cristian',
    },
    {
      matchNumber: 304,
      homeTeamName: 'CSM Arcada Galati',
      awayTeamName: 'VCM Piatra Neamt',
      dateString: '2018-08-22',
      locality: 'Campia Turzii',
      A1: 'Nastase Lucian',
      A2: 'Jianu Violeta',
    },
    {
      matchNumber: 305,
      homeTeamName: 'SCMU Craiova',
      awayTeamName: 'CS U Cluj',
      dateString: '2018-09-10',
      locality: 'Craiova',
      A1: 'Prodana Alexandru',
      A2: 'Santa Cristian',
    },
    {
      matchNumber: 306,
      homeTeamName: 'CS Unirea Dej',
      awayTeamName: 'CSM Arcada Galati',
      dateString: '2018-08-11',
      locality: 'Craiova',
      A1: 'Prodana Alexandru',
      A2: 'Jianu Violeta',
    },
    {
      matchNumber: 307,
      homeTeamName: 'CSM Bucuresti',
      awayTeamName: 'SCMU Craiova',
      dateString: '2018-09-16',
      locality: 'Craiova',
      A1: 'Prodana Alexandru',
      A2: 'Jianu Violeta',
    },
    {
      matchNumber: 308,
      homeTeamName: 'CSA Steaua Bucuresti',
      awayTeamName: 'CS Unirea Dej',
      dateString: '2018-10-14',
      locality: 'Bucuresti',
      A1: 'Nastase Lucian',
      A2: 'Jianu Violeta',
    },
    {
      matchNumber: 309,
      homeTeamName: 'CSM Campia Turzii',
      awayTeamName: 'CS U Cluj',
      dateString: '2018-11-15',
      locality: 'Zalau',
      A1: 'Serei Cristian',
      A2: 'Jianu Violeta',
    },
  ],
};
